// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe1xfViDHXu7Hsb5C5j38I3CGtN_AY0Js',
    appId: '1:609229553255:android:4c26d2021f29ef64761ec2',
    messagingSenderId: '609229553255',
    projectId: 'make-friends-app-2024',
    storageBucket: 'make-friends-app-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0YDtQ06Dm-wGcRHXv5BFeWVhrjIYcVW0',
    appId: '1:609229553255:ios:5eb64ae33e3c2e28761ec2',
    messagingSenderId: '609229553255',
    projectId: 'make-friends-app-2024',
    storageBucket: 'make-friends-app-2024.appspot.com',
    iosBundleId: 'com.example.makeFriendsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0YDtQ06Dm-wGcRHXv5BFeWVhrjIYcVW0',
    appId: '1:609229553255:ios:5eb64ae33e3c2e28761ec2',
    messagingSenderId: '609229553255',
    projectId: 'make-friends-app-2024',
    storageBucket: 'make-friends-app-2024.appspot.com',
    iosBundleId: 'com.example.makeFriendsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARtsEFD5FpAmSCK1El-e0gtGkkHCg53Ho',
    appId: '1:609229553255:web:9769702514c04774761ec2',
    messagingSenderId: '609229553255',
    projectId: 'make-friends-app-2024',
    authDomain: 'make-friends-app-2024.firebaseapp.com',
    storageBucket: 'make-friends-app-2024.appspot.com',
  );
}
